[package]
name = "async-imap"
version = "0.11.3"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
documentation = "https://docs.rs/async-imap/"
repository = "https://github.com/async-email/async-imap"
homepage = "https://github.com/async-email/async-imap"
description = "Async IMAP client for Rust"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.88"

keywords = ["email", "imap"]
categories = ["email", "network-programming"]

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "async-email/async-imap" }
is-it-maintained-open-issues = { repository = "async-email/async-imap" }

[features]
default = ["runtime-tokio"]
compress = ["async-compression"]

runtime-async-std = ["async-std", "async-compression?/futures-io"]
runtime-tokio = ["tokio", "async-compression?/tokio"]

[dependencies]
async-channel = "2.0.0"
async-compression = { version = "0.4.15", default-features = false, features = ["deflate"], optional = true }
async-std = { version = "1.8.0", default-features = false, features = ["std", "unstable"], optional = true }
base64 = "0.22.1"
bytes = "1"
chrono = { version = "0.4", default-features = false, features = ["std"] }
futures-util = {version = "0.3.15", features = ["io"] }
imap-proto = { git = "https://github.com/traumwohnung/imap-proto", branch = "phlpp/tra-950-stalwart-list-oldname-empty-esearch" }
log = "0.4.8"
nom = "8.0"
pin-project = "1"
pin-utils = "0.1.0-alpha.4"
self_cell = "1.0.1"
stop-token = "0.7"
thiserror = "1.0.9"
tokio = { version = "1", features = ["net", "sync", "time", "io-util"], optional = true }

[dev-dependencies]
async-std = { version = "1.8.0", features = ["std", "attributes"] }
pretty_assertions = "1.2"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
